---
- !mapping
  action: brightness settings
  contexts: [bdv]
  triggers: [S]
- !mapping
  action: visibility and grouping
  contexts: [bdv]
  triggers: [F6]
- !mapping
  action: help
  contexts: [bdv]
  triggers: [H, F1]
- !mapping
  action: crop
  contexts: [bdv]
  triggers: [F9]
- !mapping
  action: toggle manual transformation
  contexts: [bdv]
  triggers: [T]
- !mapping
  action: save settings
  contexts: [bdv]
  triggers: [F11]
- !mapping
  action: load settings
  contexts: [bdv]
  triggers: [F12]
- !mapping
  action: expand and focus cards panel
  contexts: [bdv]
  triggers: [P]
- !mapping
  action: collapse cards panel
  contexts: [bdv]
  triggers: [shift ESCAPE, shift P]
- !mapping
  action: record movie
  contexts: [bdv]
  triggers: [F10]
- !mapping
  action: record max projection movie
  contexts: [bdv]
  triggers: [F8]
- !mapping
  action: set bookmark
  contexts: [bdv]
  triggers: [shift B]
- !mapping
  action: go to bookmark
  contexts: [bdv]
  triggers: [B]
- !mapping
  action: go to bookmark rotation
  contexts: [bdv]
  triggers: [O]
- !mapping
  action: Preferences
  contexts: [bdv]
  triggers: [meta COMMA, ctrl COMMA]
- !mapping
  action: toggle interpolation
  contexts: [bdv]
  triggers: [I]
- !mapping
  action: toggle fused mode
  contexts: [bdv]
  triggers: [F]
- !mapping
  action: toggle grouping
  contexts: [bdv]
  triggers: [G]
- !mapping
  action: set current source 0
  contexts: [bdv]
  triggers: ['1']
- !mapping
  action: toggle source visibility 0
  contexts: [bdv]
  triggers: [shift 1]
- !mapping
  action: set current source 1
  contexts: [bdv]
  triggers: ['2']
- !mapping
  action: toggle source visibility 1
  contexts: [bdv]
  triggers: [shift 2]
- !mapping
  action: set current source 2
  contexts: [bdv]
  triggers: ['3']
- !mapping
  action: toggle source visibility 2
  contexts: [bdv]
  triggers: [shift 3]
- !mapping
  action: set current source 3
  contexts: [bdv]
  triggers: ['4']
- !mapping
  action: toggle source visibility 3
  contexts: [bdv]
  triggers: [shift 4]
- !mapping
  action: set current source 4
  contexts: [bdv]
  triggers: ['5']
- !mapping
  action: toggle source visibility 4
  contexts: [bdv]
  triggers: [shift 5]
- !mapping
  action: set current source 5
  contexts: [bdv]
  triggers: ['6']
- !mapping
  action: toggle source visibility 5
  contexts: [bdv]
  triggers: [shift 6]
- !mapping
  action: set current source 6
  contexts: [bdv]
  triggers: ['7']
- !mapping
  action: toggle source visibility 6
  contexts: [bdv]
  triggers: [shift 7]
- !mapping
  action: set current source 7
  contexts: [bdv]
  triggers: ['8']
- !mapping
  action: toggle source visibility 7
  contexts: [bdv]
  triggers: [shift 8]
- !mapping
  action: set current source 8
  contexts: [bdv]
  triggers: ['9']
- !mapping
  action: toggle source visibility 8
  contexts: [bdv]
  triggers: [shift 9]
- !mapping
  action: set current source 9
  contexts: [bdv]
  triggers: ['0']
- !mapping
  action: toggle source visibility 9
  contexts: [bdv]
  triggers: [shift 0]
- !mapping
  action: next timepoint
  contexts: [bdv]
  triggers: [CLOSE_BRACKET, M]
- !mapping
  action: previous timepoint
  contexts: [bdv]
  triggers: [OPEN_BRACKET, N]
- !mapping
  action: align XY plane
  contexts: [bdv]
  triggers: [shift Z]
- !mapping
  action: align ZY plane
  contexts: [bdv]
  triggers: [shift X]
- !mapping
  action: align XZ plane
  contexts: [bdv]
  triggers: [shift Y, shift A]
- !mapping
  action: close window
  contexts: [bdv]
  triggers: [ctrl W, meta W]
- !mapping
  action: close dialog window
  contexts: [bdv]
  triggers: [ctrl W, meta W, ESCAPE]
- !mapping
  action: drag translate
  contexts: [bdv]
  triggers: [button2, button3]
- !mapping
  action: scroll zoom
  contexts: [bdv]
  triggers: [meta scroll, shift ctrl scroll]
- !mapping
  action: axis x
  contexts: [bdv]
  triggers: [X]
- !mapping
  action: axis y
  contexts: [bdv]
  triggers: [Y]
- !mapping
  action: axis z
  contexts: [bdv]
  triggers: [Z]
- !mapping
  action: drag rotate
  contexts: [bdv]
  triggers: [button1]
- !mapping
  action: scroll browse z
  contexts: [bdv]
  triggers: [scroll]
- !mapping
  action: rotate left
  contexts: [bdv]
  triggers: [LEFT]
- !mapping
  action: rotate right
  contexts: [bdv]
  triggers: [RIGHT]
- !mapping
  action: zoom in
  contexts: [bdv]
  triggers: [UP]
- !mapping
  action: zoom out
  contexts: [bdv]
  triggers: [DOWN]
- !mapping
  action: forward z
  contexts: [bdv]
  triggers: [COMMA]
- !mapping
  action: backward z
  contexts: [bdv]
  triggers: [PERIOD]
- !mapping
  action: drag rotate fast
  contexts: [bdv]
  triggers: [shift button1]
- !mapping
  action: scroll browse z fast
  contexts: [bdv]
  triggers: [shift scroll]
- !mapping
  action: rotate left fast
  contexts: [bdv]
  triggers: [shift LEFT]
- !mapping
  action: rotate right fast
  contexts: [bdv]
  triggers: [shift RIGHT]
- !mapping
  action: zoom in fast
  contexts: [bdv]
  triggers: [shift UP]
- !mapping
  action: zoom out fast
  contexts: [bdv]
  triggers: [shift DOWN]
- !mapping
  action: forward z fast
  contexts: [bdv]
  triggers: [shift COMMA]
- !mapping
  action: backward z fast
  contexts: [bdv]
  triggers: [shift PERIOD]
- !mapping
  action: drag rotate slow
  contexts: [bdv]
  triggers: [ctrl button1]
- !mapping
  action: scroll browse z slow
  contexts: [bdv]
  triggers: [ctrl scroll]
- !mapping
  action: rotate left slow
  contexts: [bdv]
  triggers: [ctrl LEFT]
- !mapping
  action: rotate right slow
  contexts: [bdv]
  triggers: [ctrl RIGHT]
- !mapping
  action: zoom in slow
  contexts: [bdv]
  triggers: [ctrl UP]
- !mapping
  action: zoom out slow
  contexts: [bdv]
  triggers: [ctrl DOWN]
- !mapping
  action: forward z slow
  contexts: [bdv]
  triggers: [ctrl COMMA]
- !mapping
  action: backward z slow
  contexts: [bdv]
  triggers: [ctrl PERIOD]
- !mapping
  action: 2d drag translate
  contexts: [bdv]
  triggers: [button2, button3]
- !mapping
  action: 2d drag rotate
  contexts: [bdv]
  triggers: [button1]
- !mapping
  action: 2d scroll zoom
  contexts: [bdv]
  triggers: [meta scroll, scroll, shift ctrl scroll]
- !mapping
  action: 2d scroll zoom fast
  contexts: [bdv]
  triggers: [shift scroll]
- !mapping
  action: 2d scroll zoom slow
  contexts: [bdv]
  triggers: [ctrl scroll]
- !mapping
  action: 2d scroll translate
  contexts: [bdv]
  triggers: [not mapped]
- !mapping
  action: 2d scroll translate fast
  contexts: [bdv]
  triggers: [not mapped]
- !mapping
  action: 2d scroll translate slow
  contexts: [bdv]
  triggers: [not mapped]
- !mapping
  action: 2d rotate left
  contexts: [bdv]
  triggers: [LEFT]
- !mapping
  action: 2d rotate right
  contexts: [bdv]
  triggers: [RIGHT]
- !mapping
  action: 2d zoom in
  contexts: [bdv]
  triggers: [UP]
- !mapping
  action: 2d zoom out
  contexts: [bdv]
  triggers: [DOWN]
- !mapping
  action: 2d rotate left fast
  contexts: [bdv]
  triggers: [shift LEFT]
- !mapping
  action: 2d rotate right fast
  contexts: [bdv]
  triggers: [shift RIGHT]
- !mapping
  action: 2d zoom in fast
  contexts: [bdv]
  triggers: [shift UP]
- !mapping
  action: 2d zoom out fast
  contexts: [bdv]
  triggers: [shift DOWN]
- !mapping
  action: 2d rotate left slow
  contexts: [bdv]
  triggers: [ctrl LEFT]
- !mapping
  action: 2d rotate right slow
  contexts: [bdv]
  triggers: [ctrl RIGHT]
- !mapping
  action: 2d zoom in slow
  contexts: [bdv]
  triggers: [ctrl UP]
- !mapping
  action: 2d zoom out slow
  contexts: [bdv]
  triggers: [ctrl DOWN]
- !mapping
  action: 2d scroll rotate
  contexts: [bdv]
  triggers: [not mapped]
- !mapping
  action: 2d scroll rotate fast
  contexts: [bdv]
  triggers: [not mapped]
- !mapping
  action: 2d scroll rotate slow
  contexts: [bdv]
  triggers: [not mapped]
