package bdv.viewer.state.r;

public enum ViewerStateChange
{
	CURRENT_SOURCE_CHANGED,
	CURRENT_GROUP_CHANGED,
	SOURCE_ACTVITY_CHANGED,
	GROUP_ACTIVITY_CHANGED,
	SOURCE_TO_GROUP_ASSIGNMENT_CHANGED,
	GROUP_NAME_CHANGED,
	NUM_SOURCES_CHANGED,
	NUM_GROUPS_CHANGED,

	VISIBILITY_CHANGED,

	DISPLAY_MODE_CHANGED,
	INTERPOLATION_CHANGED,
	NUM_TIMEPOINTS_CHANGED,
	CURRENT_TIMEPOINT_CHANGED,
	VIEWER_TRANSFORM_CHANGED;
}
